### ISSUE TITLE
点击位置可以加入随机数吗？

### ISSUE THREAD

**Issue by ICYPOLE** [MistEO/MeoAssistance#6]
rt，感觉只是延时加随机不太够

**Comment by MistEO** [comment]
点击就是带随机的，是点击按钮内的随机位置，而且是模拟泊松分布的（偏中间位置点的概率大，越往旁边点到的概率越小）

这个默认就是开启的，~~也没法关23333~~

**Comment by ICYPOLE** [comment]
> 点击就是带随机的，是点击按钮内的随机位置，而且是模拟泊松分布的（偏中间位置点的概率大，越往旁边点到的概率越小）
> 
> 这个默认就是开启的，~也没法关23333~

hhh README里可以说一下

**Comment by MistEO** [comment]
> > 点击就是带随机的，是点击按钮内的随机位置，而且是模拟泊松分布的（偏中间位置点的概率大，越往旁边点到的概率越小）
> > 这个默认就是开启的，~也没法关23333~
> 
> hhh README里可以说一下

有道理，这就去吹一波XD
